from __future__ import annotations

from .models import MetricDefinition


def default_metric_registry() -> list[MetricDefinition]:
    return [
        MetricDefinition(
            metric_key="deflection_rate",
            label="Deflection Rate",
            description="Share of eligible conversations resolved by AI without human transfer.",
            canonical_unit="percent",
            display_unit="%",
            value_kind="rate",
            direction="higher_is_better",
            min_value=0.0,
            max_value=100.0,
            default_lookback_days=30,
            minimum_sample_size=20,
            eligibility_rule="eligible conversations with a known final outcome",
            calculation_notes="Requires controlled outcomes and excludes conversations with unknown final disposition.",
            requires_outcome_taxonomy=True,
            measurement_sources=["conversations", "realtime_events"],
        ),
        MetricDefinition(
            metric_key="csat",
            label="CSAT",
            description="Customer satisfaction score normalized to a 0-100 scale.",
            canonical_unit="score_100",
            display_unit="pts",
            value_kind="score",
            direction="higher_is_better",
            min_value=0.0,
            max_value=100.0,
            default_lookback_days=30,
            minimum_sample_size=15,
            calculation_variant="normalized_average_score",
            eligibility_rule="conversations with a valid survey or equivalent sentiment input",
            auto_measurable=False,
            measurement_sources=["conversations"],
        ),
        MetricDefinition(
            metric_key="resolution_rate",
            label="Resolution Rate",
            description="Share of eligible conversations that ended resolved.",
            canonical_unit="percent",
            display_unit="%",
            value_kind="rate",
            direction="higher_is_better",
            min_value=0.0,
            max_value=100.0,
            default_lookback_days=30,
            minimum_sample_size=20,
            eligibility_rule="eligible conversations with explicit resolution outcomes",
            requires_outcome_taxonomy=True,
            measurement_sources=["conversations"],
        ),
        MetricDefinition(
            metric_key="average_handle_time",
            label="Average Handle Time",
            description="Average duration of eligible completed conversations in seconds.",
            canonical_unit="seconds",
            display_unit="sec",
            value_kind="duration",
            direction="lower_is_better",
            min_value=0.0,
            max_value=None,
            default_lookback_days=30,
            minimum_sample_size=20,
            eligibility_rule="completed conversations with reliable start and end timestamps",
            measurement_sources=["conversations", "turn_traces", "realtime_events"],
        ),
        MetricDefinition(
            metric_key="first_contact_resolution",
            label="First Contact Resolution",
            description="Share of resolved cases that did not recur within the defined follow-up window.",
            canonical_unit="percent",
            display_unit="%",
            value_kind="rate",
            direction="higher_is_better",
            min_value=0.0,
            max_value=100.0,
            default_lookback_days=30,
            minimum_sample_size=20,
            eligibility_rule="resolved cases with stable customer and issue linkage",
            requires_outcome_taxonomy=True,
            auto_measurable=False,
            measurement_sources=["conversations"],
        ),
        MetricDefinition(
            metric_key="transfer_rate",
            label="Transfer Rate",
            description="Share of eligible conversations transferred to a human.",
            canonical_unit="percent",
            display_unit="%",
            value_kind="rate",
            direction="lower_is_better",
            min_value=0.0,
            max_value=100.0,
            default_lookback_days=30,
            minimum_sample_size=20,
            eligibility_rule="eligible conversations with explicit transfer outcomes",
            requires_outcome_taxonomy=True,
            measurement_sources=["conversations", "realtime_events"],
        ),
        MetricDefinition(
            metric_key="abandonment_rate",
            label="Abandonment Rate",
            description="Share of eligible started conversations abandoned before resolution or transfer.",
            canonical_unit="percent",
            display_unit="%",
            value_kind="rate",
            direction="lower_is_better",
            min_value=0.0,
            max_value=100.0,
            default_lookback_days=30,
            minimum_sample_size=20,
            eligibility_rule="started conversations with explicit abandonment handling",
            requires_outcome_taxonomy=True,
            measurement_sources=["conversations", "realtime_events"],
        ),
        MetricDefinition(
            metric_key="cost_per_conversation",
            label="Cost Per Conversation",
            description="Mean direct system cost per eligible conversation.",
            canonical_unit="usd",
            display_unit="$",
            value_kind="currency",
            direction="lower_is_better",
            min_value=0.0,
            max_value=None,
            default_lookback_days=30,
            minimum_sample_size=10,
            eligibility_rule="conversations with linked provider cost records",
            measurement_sources=["provider_cost_records", "tool_invocations", "conversations"],
        ),
        MetricDefinition(
            metric_key="containment_rate",
            label="Containment Rate",
            description="Share of eligible conversations handled inside the AI support flow under explicit containment rules.",
            canonical_unit="percent",
            display_unit="%",
            value_kind="rate",
            direction="higher_is_better",
            min_value=0.0,
            max_value=100.0,
            default_lookback_days=30,
            minimum_sample_size=20,
            eligibility_rule="eligible conversations with explicit containment outcomes",
            requires_outcome_taxonomy=True,
            contained_outcomes=["resolved"],
            measurement_sources=["conversations", "realtime_events"],
        ),
        MetricDefinition(
            metric_key="sentiment_score",
            label="Sentiment Score",
            description="Mean normalized conversation sentiment score on a 0-100 scale.",
            canonical_unit="score_100",
            display_unit="pts",
            value_kind="score",
            direction="higher_is_better",
            min_value=0.0,
            max_value=100.0,
            default_lookback_days=30,
            minimum_sample_size=15,
            eligibility_rule="conversations with valid sentiment scoring inputs",
            auto_measurable=False,
            measurement_sources=["conversations"],
        ),
    ]


def metric_registry_by_key() -> dict[str, MetricDefinition]:
    return {definition.metric_key: definition for definition in default_metric_registry()}
