"""KPI domain models. Business logic independent of persistence.

These models represent KPI concepts as they exist in the kernel.
They do NOT include:
- Primary keys (generated by DB)
- Implementation details (table names, indexes)
- API-specific fields (computed_fields from projections)

What they DO include:
- Business rules (validators)
- Domain operations (methods)
- Core identity fields
"""

from datetime import datetime, timezone
from typing import Literal, Optional
from uuid import uuid4

from pydantic import BaseModel, ConfigDict, Field, field_validator


def utcnow() -> datetime:
    """Current UTC time."""
    return datetime.now(timezone.utc)


# ─────────────────────────────────────────────────────────────────────
# KPI-specific enums
# ─────────────────────────────────────────────────────────────────────

MetricDirection = Literal["higher_is_better", "lower_is_better"]
MetricUnit = Literal["percent", "score_100", "seconds", "usd"]
ScopeKind = Literal["organization", "agent", "workflow", "channel", "segment", "campaign", "custom"]
GoalStatus = Literal["draft", "active", "paused", "completed", "archived"]
ObservationKind = Literal["baseline", "scheduled_refresh", "manual_entry", "experiment_readout"]


# ─────────────────────────────────────────────────────────────────────
# Goal Definition
# ─────────────────────────────────────────────────────────────────────


class GoalDefinition(BaseModel):
    """A KPI goal to track and optimize.

    Core domain model for KPI goals. Represents what the business wants
    to measure and improve.
    """

    definition_id: str = Field(
        default_factory=lambda: str(uuid4()),
        description="Unique identifier for this goal.",
    )
    organization_id: str = Field(
        description="Organization that owns this goal.",
    )
    kind: ScopeKind = Field(
        description="Scope of this goal: organization, agent, workflow, etc.",
    )
    name: str = Field(
        min_length=1,
        max_length=255,
        description="Human-readable goal name.",
    )
    description: Optional[str] = Field(
        default=None,
        max_length=2000,
        description="Long-form description of what this goal measures.",
    )
    metric_key: str = Field(
        min_length=1,
        max_length=255,
        description="Dotted path to the metric in conversation data. E.g., 'conversation.fcr_score'",
    )
    metric_direction: MetricDirection = Field(
        description="Is higher or lower better?",
    )
    metric_unit: MetricUnit = Field(
        description="Unit of measurement: percent, score, seconds, usd.",
    )
    target_value: float = Field(
        ge=0,
        description="Target value for this goal.",
    )
    baseline_value: Optional[float] = Field(
        default=None,
        ge=0,
        description="Baseline value for comparison.",
    )
    status: GoalStatus = Field(
        default="draft",
        description="Draft, active, paused, completed, or archived.",
    )
    created_by: Optional[str] = Field(
        default=None,
        description="User ID of creator.",
    )
    updated_by: Optional[str] = Field(
        default=None,
        description="User ID of last updater.",
    )
    tags: list[str] = Field(
        default_factory=list,
        max_length=10,
        description="Searchable tags.",
    )
    created_at: datetime = Field(
        default_factory=utcnow,
        description="When this goal was created.",
    )
    updated_at: datetime = Field(
        default_factory=utcnow,
        description="When this goal was last updated.",
    )

    @field_validator("metric_key")
    @classmethod
    def validate_metric_key_format(cls, v: str) -> str:
        """Metric key must be dot-separated identifiers."""
        if not v or not all(
            part.replace("_", "").isalnum() for part in v.split(".")
        ):
            raise ValueError(
                "metric_key must be alphanumeric identifiers separated by dots (e.g., 'conversation.fcr_score')"
            )
        return v

    @field_validator("target_value")
    @classmethod
    def validate_target_is_positive(cls, v: float) -> float:
        """Target must be positive."""
        if v <= 0:
            raise ValueError("target_value must be > 0")
        return v

    @field_validator("baseline_value")
    @classmethod
    def validate_baseline(cls, v: Optional[float]) -> Optional[float]:
        """Baseline, if provided, must be positive."""
        if v is not None and v < 0:
            raise ValueError("baseline_value must be >= 0")
        return v

    def is_on_track(self, current_value: float) -> bool:
        """Check if current value is on track to meet target.

        Simple heuristic: within 90% of target (for higher-is-better)
        or within 110% of target (for lower-is-better).
        """
        if current_value is None:
            return False

        if self.metric_direction == "higher_is_better":
            return current_value >= self.target_value * 0.9
        else:
            return current_value <= self.target_value * 1.1

    model_config = ConfigDict(
        json_schema_extra={
            "examples": [
                {
                    "definition_id": "goal_fcr_2024",
                    "organization_id": "org_acme",
                    "kind": "agent",
                    "name": "First-Call Resolution",
                    "description": "Percentage of conversations resolved on first contact",
                    "metric_key": "conversation.fcr_score",
                    "metric_direction": "higher_is_better",
                    "metric_unit": "percent",
                    "target_value": 85.0,
                    "baseline_value": 72.0,
                    "status": "active",
                }
            ]
        }
    )


# ─────────────────────────────────────────────────────────────────────
# Goal Execution (Observation)
# ─────────────────────────────────────────────────────────────────────


class GoalExecution(BaseModel):
    """An observation of a goal. When did we measure progress?

    Each execution records a single measurement at a point in time.
    Multiple executions over time show progress toward the goal.
    """

    execution_id: str = Field(
        default_factory=lambda: str(uuid4()),
        description="Unique identifier for this execution.",
    )
    organization_id: str = Field(
        description="Organization that owns this execution.",
    )
    definition_id: str = Field(
        description="ID of the goal definition being measured.",
    )
    observation_kind: ObservationKind = Field(
        description="Type of observation: baseline, refresh, manual, experiment.",
    )
    observed_value: float = Field(
        description="The measured value.",
    )
    confidence: float = Field(
        default=1.0,
        ge=0.0,
        le=1.0,
        description="Confidence in this measurement (0-1).",
    )
    observed_at: datetime = Field(
        description="When the observation was taken.",
    )
    metadata_json: dict = Field(
        default_factory=dict,
        max_length=100,
        description="Additional context (source system, tags, etc.).",
    )
    created_at: datetime = Field(
        default_factory=utcnow,
        description="When this execution was recorded.",
    )
    updated_at: datetime = Field(
        default_factory=utcnow,
        description="When this execution was last updated.",
    )

    model_config = ConfigDict(
        json_schema_extra={
            "examples": [
                {
                    "execution_id": "exec_20240101_fcr",
                    "organization_id": "org_acme",
                    "definition_id": "goal_fcr_2024",
                    "observation_kind": "scheduled_refresh",
                    "observed_value": 78.5,
                    "confidence": 0.95,
                    "observed_at": "2024-01-01T00:00:00Z",
                    "metadata_json": {"source": "analytics", "period": "weekly"},
                }
            ]
        }
    )


# ─────────────────────────────────────────────────────────────────────
# Domain Events
# ─────────────────────────────────────────────────────────────────────


class GoalDefinitionCreated(BaseModel):
    """Event: goal definition was created."""

    definition_id: str
    organization_id: str
    kind: ScopeKind
    name: str
    created_by: Optional[str] = None
    timestamp: datetime = Field(default_factory=utcnow)


class GoalDefinitionUpdated(BaseModel):
    """Event: goal definition was updated."""

    definition_id: str
    organization_id: str
    changes: dict  # What changed
    updated_by: Optional[str] = None
    timestamp: datetime = Field(default_factory=utcnow)


class GoalObservationRecorded(BaseModel):
    """Event: observation recorded for a goal."""

    execution_id: str
    definition_id: str
    organization_id: str
    observed_value: float
    observation_kind: ObservationKind
    timestamp: datetime = Field(default_factory=utcnow)
